### ISSUE TITLE
升级到1.0.0后，使用出错了。

### ISSUE THREAD

**Issue by ws4934** [kisstar/electron-events#11]
App threw an error during load
file:///D:/WebstormProjects/test/node_modules/electron-events/dist-electron/index.mjs:8
import { ipcMain, BrowserWindow, ipcRenderer } from "electron";

使用的"electron": "^31.0.2"，之前的0.3.2版本没问题捏

**Comment by kisstar** [comment]
我将 electron 升级到了 v33 未能复现您提到的问题，可以的话尽量补充下复现问题的路径，最好是能提供一个复现问题的demo😊

**Comment by ws4934** [comment]
抱歉打扰到您。我使用的[electron-vite](https://electron-vite.org/)，typeScript脚手架创建的项目，并且启用了ESM。初始项目并安装electron-events，按照README文档不可使用，比较菜，不知道什么问题😂。

**Comment by kisstar** [comment]
尝试了下 electron-vite 看起来也是正常的：
```bash
$ node -v
v20.18.0

$ pnpm create @quick-start/electron my-app --template vue
../Library/pnpm/store/v3/tmp/dlx-29901   |   +8 +
../Library/pnpm/store/v3/tmp/dlx-29901   | Progress: resolved 8, reused 7, downloaded 1, added 8, done
✔ Add TypeScript? … No / Yes
✔ Add Electron updater plugin? … No / Yes
✔ Enable Electron download mirror proxy? … No / Yes

$ pnpm add electron-events
# 接着参照 electron-events 的 README 说明进行使用

$ cd my-app && pnpm install && pnpm dev
dev server running for the electron renderer process at:

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose

start electron app...
```

可能需要更多的信息才能复现您的问题。

**Comment by ws4934** [comment]
感谢您的回复😊
我尝试了electron-vite在不启用ESM的情况下可以正常使用，启用ESM后就会报错(无论方式一还是二)。
参见：[Enabling ESM](https://electron-vite.org/guide/dev#enabling-esm)

**Comment by kisstar** [comment]
看起来是在开启 electron ESM 之后，进程通信模块不能跨进程导入，为此需要将 preload 的部分也独立出来，很快将发布一个新的版本来做到这一点，然后可以再试试。
