### ISSUE TITLE
SyntaxError: The requested module 'electron' does not provide an export named 'ipcRenderer'

### ISSUE THREAD

**Issue by baofengs** [kisstar/electron-events#13]
### Electron Version

33.2.0

### electron-events Version

1.0.1

### What operating system(s) are you using?

macOS

### Operating System Version

macOS 13.5 (22G74)

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior
进程能正常启动

### Actual Behavior

SyntaxError: The requested module 'electron' does not provide an export named 'ipcRenderer'
![image](https://github.com/user-attachments/assets/4d5d154b-1186-4ad3-a323-adff896007fb)

**Comment by baofengs** [comment]
1. 使用 vite-plugin-electron/simple 搭建项目
2. node 版：v21.1.0
3. type: module

**Comment by kisstar** [comment]
按照下面的步骤，看起来一切正常：
```bash
pnpm create vite my-app --template vanilla-ts
cd my-app
pnpm install
pnpm add -D electron
pnpm add -D vite-plugin-electron
pnpm add -D vite-plugin-electron-renderer
# 按照 vite-plugin-electron 中 Quick Setup 中的部分进行操作
# 将示例的入口文件从 dist-electron/main.mjs 改为 dist-electron/main.js
touch electron/preload.ts
pnpm add electron-events
# 按照 electron-events 中的 Usage 部分进行操作，注意在 main.ts 中配置加载预加载脚本
pnpm run dev
```
可以尝试提供下更详细的复现路径，或者提供一个 DEMO。

**Comment by baofengs** [comment]
@kisstar 问题解决了，写法问题
0.3.2 中可以直接使用 `import { useEvents } from 'electron-events';` 方式在主进程中引入 useEvents
1.0.1 中得使用 `import { useEvents } from 'electron-events/main';` 方式引入，否则就会出现以上问题

**Comment by baofengs** [comment]
@kisstar 但是发现另一个问题，在 0.3.2 中可以直接使用这种方式将 events 暴露到 window 上
```js
import { useEvents } from 'electron-events';
const events = useEvents();
contextBridge.exposeInMainWorld('electronApi', {
    events,
  }
});
```

但是采用新写法之后，这种写法失效了

有一个场景，我有另一个前端项目，使用 iframe 方式嵌入到 renderer 页面中使用，然后在 iframe 页面中需要使用到 useEvens 跟外边的进程进行通信，这种应该怎么处理？在 iframe 项目里也 install 一下 electron-events？还是有其他办法注入进去？
