### ISSUE TITLE
提示了两个错误:ipcMain和BrowserWindow

### ISSUE THREAD

**Issue by nikeekin** [kisstar/electron-events#8]
非常抱歉,因为我的水平太菜,不知道是什么原因造成的,只能把错误信息贴上来,麻烦给看一下.谢谢
X [ERROR] No matching export in "node_modules/.vite-electron-renderer/electron.mjs" for import "ipcMain"      

    node_modules/electron-events/dist-electron/index.mjs:8:9:
      8 │ import { ipcMain, BrowserWindow, ipcRenderer } from "electron";
        ╵          ~~~~~~~

X [ERROR] No matching export in "node_modules/.vite-electron-renderer/electron.mjs" for import "BrowserWindow"

    node_modules/electron-events/dist-electron/index.mjs:8:18:
      8 │ import { ipcMain, BrowserWindow, ipcRenderer } from "electron";

**Comment by kisstar** [comment]
看起来这不是您的错误，由于当前 [electron-events](https://github.com/kisstar/electron-events) 将主进程和渲染进程的代码都打包到了一个文件中，所以直接在渲染进程进行引用时会导入主进程独有的模块，从而导致上面的错误。

很抱歉，文档中使用实例中存在的错误误导了您。

目前，对于渲染进程的部分，您可以参考 [demo](https://github.com/kisstar/electron-events/tree/main/packages/demo) 中的使用方式通过 [预加载脚本](https://www.electronjs.org/zh/docs/latest/tutorial/tutorial-preload) 在渲染进程中进行使用。

**Comment by kisstar** [comment]
现在，[README](https://github.com/kisstar/electron-events/blob/main/README-zh_CN.md) 文档中已经完善了预加载脚本部分的说明，欢迎继续使用和反馈。
