### ISSUE TITLE
 events.off 不生效

### ISSUE THREAD

**Issue by Lin-Ya** [kisstar/electron-events#9]
os: macos 14.4.1
感谢作者开源这个项目，我看完了juejin的文章觉得这个设计很巧妙，于是进行了调试。
我 fork 了一份，进行了如下更改: [commit](https://github.com/Lin-Ya/electron-events/commit/0a1ab4203365f82baa45b67d9b349a15f7e90576?w=1)
简单来说就是在 app 窗口触发了主进程的操作，主进程将会向 app 窗口发送一次 TEST_CHANNEL 的事件。app 窗口监听这个事件进行输出，并取消监听。
```ts
function handle(params: any) {
  console.log('from main,to app', params);
  // @error 出现无法取消监听，第二次触发依旧会进入 handle 函数的执行。
  events.off('main', TEST_CHANNEL, handle);
}
events.on('main', TEST_CHANNEL, handle);
```
但实际上并没有取消成功，依旧能重复触发。我对此 debug 了一段时间，发现在源码进行 _off 函数执行的阶段，resEventName 也是正确的，但就是没能成功注销。

**Comment by kisstar** [comment]
是的，看起来这里确实有一些问题，可能是因为 Electron 上下文隔离机制引起的，我猜测：

> 在这里注册和取消时传递的函数被 Electron 内部上下文包装，当尝试访问这个函数时，它看到的是 Electron 提供的一个代理或封装，而不是函数的实际源代码，因此前后2个函数并不相同。

我想到一个解决方案是将渲染进程的代码与 Electron 完全隔离，进程通信相关的依赖由 preload 提供，在渲染进程中首次使用时再注入进去。
这种方案会导致使用方式上会有所调整，在没有更好的方案之前，我会先这样调整下，以待后续。
